radar_cf = {
    "ACRR": "ACRR",
    "ASHR": "ASHR",
    "BRDR": "BRDR",
    "CCORH": "CCOR_h",
    "CCORV": "CCOR_v",
    "CLASS": "CLASS",
    "CPA": "CPA",
    "CSHR": "CSHR",
    "DBZ": "radar_equivalent_reflectivity_factor_h",
    "DBZH": "radar_equivalent_reflectivity_factor_h",
    "DBZV": "radar_equivalent_reflectivity_factor_v",
    "ESHR": "ESHR",
    "HGHT": "HGHT",
    "HI": "HI",
    "HSHR": "HSHR",
    "KDP": "radar_specific_differential_phase_hv",
    "LDR": "radar_linear_depolarization_ratio",
    "LZDR": "radar_differential_reflectivity_hv",
    "MESH": "MESH",
    "OSHR": "OSHR",
    "PHIDP": "radar_differential_phase_hv",
    "PIA": "PIA",
    "POH": "POH",
    "POR": "POR",
    "POSH": "POSH",
    "PSH": "PSH",
    "PSV": "PSV",
    "QIND": "QIND",
    "RATE": "radar_estimated_precipitation_rate",
    "RHOHV": "radar_correlation_coefficient_hv",
    "RSHR": "RSHR",
    "SNR": "radar_signal_to_noise_ratio",
    "SNRHC": "radar_signal_to_noise_ratio_copolar_h",
    "SNRHX": "radar_signal_to_noise_ratio_crosspolar_h",
    "SNRVC": "radar_signal_to_noise_ratio_copolar_v",
    "SNRVX": "radar_signal_to_noise_ratio_crosspolar_v",
    "SQI": "SQI",
    "SQIH": "SQIH",
    "SQIV": "SQIV",
    "TH": "radar_linear_equivalent_reflectivity_factor_h",
    "TSHR": "TSHR",
    "TV": "radar_linear_equivalent_reflectivity_factor_v",
    "UKDP": "UKDP",
    "ULDR": "ULDR",
    "UPHIDP": "UPHIDP",
    "UPSPH": "UPSPH",
    "UPSPV": "UPSPV",
    "URATE": "URATE",
    "URHOHV": "URHOHV",
    "USNRHC": "USNRHC",
    "USNRVC": "USNRVC",
    "USQIH": "USQIH",
    "USQIV": "USQIV",
    "UVRADH": "UVRADH",
    "UVRADV": "UVRADV",
    "UWND": "UWND",
    "UWRADH": "UWRADH",
    "UWRADV": "UWRADV",
    "UZDR": "UZDR",
    "VIL": "VIL",
    "VRAD": "radial_velocity_of_scatterers_away_from_instrument_h",
    "VRADDH": "VRADDH",
    "VRADDV": "VRADDV",
    "VRADH": "radial_velocity_of_scatterers_away_from_instrument_h",
    "VRADV": "radial_velocity_of_scatterers_away_from_instrument_v",
    "VSHR": "VSHR",
    "VWND": "VWND",
    "WRAD": "radar_doppler_spectrum_width_h",
    "WRADH": "radar_doppler_spectrum_width_h",
    "WRADV": "radar_doppler_spectrum_width_v",
    "ZDR": "radar_differential_reflectivity_hv"
}

odim_acdd_attrs = [
    "license",
    "naming_authority",
    "institution",
    "creator_name",
    "creator_email",
    "creator_url",
    "publisher_name",
    "publisher_email",
    "publisher_url",
    "creator_type",
    "creator_institution",
    "publisher_type",
    "publisher_institution"
]

country_naming_auth = {
    "at": "at.austrocontrol",
    "be": "be.meteo",
    "ch": "ch.meteoswiss",
    "mt": "com.maltairport",
    "cy": "cy.gov.moa.dom",
    "cz": "cz.chmi",
    "de": "de.dwd",
    "dk": "dk.dmi",
    "ee": "ee.envir",
    "es": "es.aemet",
    "fi": "fi.fmi",
    "fr": "fr.meteo",
    "gr": "gr.hnms",
    "hr": "hr.dhz.cirus",
    "hu": "hu.met",
    "ie": "ie.met",
    "il": "il.gov.ims",
    "is": "is.vedur",
    "je": "je.gov.jerseymet",
    "lt": "lt.meteo",
    "lu": "lu.etat.airport",
    "lv": "lv.lvgmc",
    "md": "md.gov.meteo",
    "nl": "nl.knmi",
    "no": "no.met",
    "pl": "pl.imgw",
    "pt": "pt.ipma",
    "ro": "ro.meteoromania",
    "rs": "rs.gov.hidmet",
    "se": "se.smhi",
    "si": "si.gov",
    "sk": "sk.shmu",
    "uk": "uk.gov.metoffice"
}
